# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ly-i7RqBpjzvRr1IPRzk8VZyOsB7LFjW
"""

import pandas as pd
guruh=pd.DataFrame({
    'Ism':['Oybek','Dilshodbek','Sarvarbek','Imomali',"Jo'rabek",'Alisher','Muhammaddiyor','Asrorbek','Muhammadsharif','Ilhomjon'    ],
    'Familiya':['Turonboyev','Ikromaliyev','Shakirjonov','Nuriddinjonov','Tursunaliyev','Erkinov','Tolibjonov','Alimqulov','Sobirjonov','Abduhakimov'  ],
    'Manzili':[ 'Beshariq tumani','Angren tumani',"Bag'dod",'Quvasoy',"Bag'dod",'Beshariq',"Bag'dod",'Namangan','Namangan','Vodil'],
    'Tel raqami':['+998940520123','+998940520123','+998940520123','+998940520123','+998940520123','+998940520123','+998940520123','+998940520123','+998940520123','+998940520123']
})
print (guruh)

guruh.to_excel('guruh.xlsx')